#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("GravatarMobile_Android.Resource", IsApplication=true)]

namespace GravatarMobile_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GravatarMobile.Droid.Resource.Attribute.initial_style = global::GravatarMobile_Android.Resource.Attribute.initial_style;
			global::GravatarMobile.Droid.Resource.Id.round = global::GravatarMobile_Android.Resource.Id.round;
			global::GravatarMobile.Droid.Resource.Id.square = global::GravatarMobile_Android.Resource.Id.square;
			global::GravatarMobile.Droid.Resource.String.library_name = global::GravatarMobile_Android.Resource.String.library_name;
			global::GravatarMobile.Droid.Resource.Styleable.GravatarView = global::GravatarMobile_Android.Resource.Styleable.GravatarView;
			global::GravatarMobile.Droid.Resource.Styleable.GravatarView_initial_style = global::GravatarMobile_Android.Resource.Styleable.GravatarView_initial_style;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int initial_style = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040005
			public const int btnCircle = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int btnLoad = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int btnSquare = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int edtEmail = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int imgGravatar = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int linearLayout1 = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int round = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int square = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] GravatarView = new int[]
			{
					2130771968};
			
			// aapt resource value: 0
			public const int GravatarView_initial_style = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
